pipeline {
    agent {
        docker {
            image 'ruby'
            args '--network rocklov-network'
        }
    }

    stages {
        stage('Prep') {
            steps {
                sh 'cd rock-lov/web && bundle install'
            }
        }
        stage('Testing') {
            steps {
                sh 'cd rock-lov/web && rake local_seeds'
            }
        }
        stage('UAT') {
            steps {
                echo 'Aguardando testes de aceitação.'
                input message: 'Podemos ir para produção?'
            }
        }
        stage('Prod') {
            steps {
                echo 'WebApp pronta para produção :)'
            }
        }
    }
    post {
        always {
            echo 'to do'
        }
    }
}