pipeline {
    agent {
        docker {
            image 'ruby'
        }
    }

    stages {
        stage('Prep') {
            steps {
                sh 'cd rock-lov/api && bundle install'
            }
        }
        stage('Testing') {
            steps {
                sh 'cd rock-lov/api && rspec'
            }
        }
    }
}